import type { CmsPageBlock } from "@/cms/types/blocks";
import type { CmsBlockFallbacks } from "@/cms/types/page";
import {
  DEFAULT_ACTION_PANEL_BLOCK,
  DEFAULT_ACTION_PANEL_BLOCK_FALLBACK,
} from "./actionPanel";
import {
  DEFAULT_CTA_SECTION_BLOCK,
  DEFAULT_CTA_SECTION_BLOCK_FALLBACK,
} from "./ctaSection";
import { DEFAULT_HERO_BLOCK, DEFAULT_HERO_BLOCK_FALLBACK } from "./hero";
export { DEFAULT_HERO3_BLOCK } from "./hero3";
import {
  DEFAULT_HIGHLIGHTS_BLOCK,
  DEFAULT_HIGHLIGHTS_BLOCK_FALLBACK,
} from "./highlights";
import {
  DEFAULT_SIDE_TABS_BLOCK,
  DEFAULT_SIDE_TABS_BLOCK_FALLBACK,
} from "./sideTabs";
import {
  DEFAULT_TESTIMONIALS_BLOCK,
  DEFAULT_TESTIMONIALS_BLOCK_FALLBACK,
} from "./testimonials";

export const DEFAULT_CMS_BLOCK_FALLBACKS: CmsBlockFallbacks = {
  actionPanel: DEFAULT_ACTION_PANEL_BLOCK_FALLBACK,
  ctaSection: DEFAULT_CTA_SECTION_BLOCK_FALLBACK,
  hero: DEFAULT_HERO_BLOCK_FALLBACK,
  highlights: DEFAULT_HIGHLIGHTS_BLOCK_FALLBACK,
  sideTabs: DEFAULT_SIDE_TABS_BLOCK_FALLBACK,
  testimonials: DEFAULT_TESTIMONIALS_BLOCK_FALLBACK,
};

export const DEFAULT_CMS_PAGE_BLOCKS: CmsPageBlock[] = [
  DEFAULT_HERO_BLOCK,
  DEFAULT_ACTION_PANEL_BLOCK,
  DEFAULT_CTA_SECTION_BLOCK,
  DEFAULT_SIDE_TABS_BLOCK,
  DEFAULT_HIGHLIGHTS_BLOCK,
  DEFAULT_TESTIMONIALS_BLOCK,
];
