import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { draftMode } from "next/headers";
import {VisualEditing} from 'next-sanity'
import {DisableDraftMode} from '../components/DisableDraftMode'
import Header from "../components/Header";
import Footer from "../components/Footer";


export const metadata: Metadata = {
  title: "Sanity Visual Test",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const {isEnabled} = await draftMode()

  return (
     <html lang="en">
         <body className="min-h-screen bg-white text-gray-900 antialiased dark:bg-gray-950 dark:text-gray-100">
          <div className="flex  flex-col">
         <Header />
        <main className="flex-1">{children}</main>
        {(await draftMode()).isEnabled && (
          <>
            <VisualEditing />
            <DisableDraftMode />
         
          </>
        )}
           <Footer />
           </div>
      </body>
    </html>
  )
}